name: oh_diosa_nails
description: "Reserva de citas para negocios locales."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true